### ISSUE TITLE
Make command-line interface easier to use (node)

### ISSUE THREAD

**Issue by romgrk** [WebReflection/echomd#1]
One would usually expect to be able to either pipe text into a command, or specify a filepath as an argument to the command, and have it display it. The current interface in somewhat awkward.

Things one would expect to work:
```sh
$ curl https://example.com/readme.md | echomd
$ echomd < readme.md
$ echomd readme.md
```

Things that actually work:
```sh
$ echomd "$(curl https://example.com/readme.md)"
$ echomd "$(cat readme.md)"
```

**Comment by WebReflection** [comment]
> The current interface in somewhat awkward

This is a replacement for the native `echo` which works exactly the same.

None of your first 3 examples would produce what you expect with `echo` so I wonder how come you consider this one weird when it has same name and purpose of the original.

**Comment by romgrk** [comment]
You're right, I didn't noted that it was intended to behave as `echo`. I think the use-cases listed are more frequent, but be free to close if you prefer to keep it as-is.

**Comment by WebReflection** [comment]
Piped might have sense but third example doesn't, that's just text to echo to me, no special meaning.

Anyway, once more people will ask for this I'll try to find some time to implement that.
