### ISSUE TITLE
Support italic

### ISSUE THREAD

**Issue by romgrk** [WebReflection/echomd#2]
![screenshot from 2018-08-30 17-37-20](https://user-images.githubusercontent.com/1423607/44880749-6594b700-ac7b-11e8-8676-152aa8e9dea9.png)

**Comment by WebReflection** [comment]
Have you read the readme ?

[bold](https://github.com/WebReflection/echomd#bold)

> Using one or two asterisks would produce some bold text. `*this*` or `**this**` will produce identical text, preserving the semantic original meaning of the *, showing up consistently bold in every platform.

[underline](https://github.com/WebReflection/echomd#underline)
> Following same cross platform consistency reason, using one or more underscores will produce an underlined text. `_this_` and `__this__` are equivalent, and it's possible combine both bold and underline at once via `*_this_*` or `_*that*_`.

Italic wouldn't exist so it makes no sense to have it here.

This is not a 100% Markdown replacement, this is a convenient way to show cross platform **similar** markdown in terminal.
