### ISSUE TITLE
Literal strings within syntax

### ISSUE THREAD

**Issue by brettz9** [WebReflection/echomd#3]
I'd like to provide some literal strings (e.g., as found in test results from Tressa), but echomd ends up treating these as its own syntax. Is there a way, or would you be open to adding a way, to embed literal strings within a portion of a single echomd string (which may otherwise contain special formatting)?

**Comment by WebReflection** [comment]
not sure I understand the issue ... literal strings are identical to every other char but you can surround literal strings with more literal strings or with spaces as it is for * or _ and others
